macro(configure_protobuf)
    message(STATUS "Configuring protobuf...")
    option(protobuf_BUILD_TESTS "" OFF)
    option(protobuf_BUILD_EXAMPLES "" OFF)
    option(protobuf_BUILD_SHARED_LIBS "" ON)
    option(protobuf_BUILD_PROTOC_BINARIES "" ON)
    add_definitions(-DPROTOBUF_USE_DLLS)
    add_subdirectory(${PROJECT_SOURCE_DIR}/third_party/protobuf/cmake)
    add_executable(protobuf::protoc ALIAS protoc)
    add_library(protobuf::libprotobuf ALIAS libprotobuf)
    add_library(protobuf::libprotobuf-lite ALIAS libprotobuf-lite)
endmacro()
