macro(configure_protobuf)
    message(STATUS "Configuring protobuf...")
    option(protobuf_BUILD_TESTS "" OFF)
    option(protobuf_BUILD_EXAMPLES "" OFF)
    if (${CMAKE_SYSTEM_NAME} STREQUAL "Android")
        option(protobuf_BUILD_PROTOC_BINARIES "" OFF)
    else()
        option(protobuf_BUILD_PROTOC_BINARIES "" ON)
    endif()
    add_subdirectory(${PROJECT_SOURCE_DIR}/third_party/protobuf/cmake)
    if (NOT ${CMAKE_SYSTEM_NAME} STREQUAL "Android")
        add_executable(protobuf::protoc ALIAS protoc)
    endif()
    add_library(protobuf::libprotobuf ALIAS libprotobuf)
    add_library(protobuf::libprotobuf-lite ALIAS libprotobuf-lite)
endmacro()
